// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// capacitive_touch //
// ---------------- //

#define capacitive_touch_wrap_target 0
#define capacitive_touch_wrap 11
#define capacitive_touch_pio_version 0

#define capacitive_touch_offset_wait_for_restart 11u

static const uint16_t capacitive_touch_program_instructions[] = {
            //     .wrap_target
    0xa02b, //  0: mov    x, ~null
    0xe048, //  1: set    y, 8
    0xe081, //  2: set    pindirs, 1
    0xef00, //  3: set    pins, 0                [15]
    0xe080, //  4: set    pindirs, 0
    0xe001, //  5: set    pins, 1
    0x00c8, //  6: jmp    pin, 8
    0x0046, //  7: jmp    x--, 6
    0x0082, //  8: jmp    y--, 2
    0xa0c1, //  9: mov    isr, x
    0x8020, // 10: push   block
    0x000b, // 11: jmp    11
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program capacitive_touch_program = {
    .instructions = capacitive_touch_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = capacitive_touch_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config capacitive_touch_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + capacitive_touch_wrap_target, offset + capacitive_touch_wrap);
    sm_config_set_sideset(&c, 1, true, false);
    return c;
}
#endif

