// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// PioI2S_out //
// ---------- //

#define PioI2S_out_wrap_target 0
#define PioI2S_out_wrap 8
#define PioI2S_out_pio_version 0

#define PioI2S_out_offset_entry_point 0u

static const uint16_t PioI2S_out_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xa047, //  1: mov    y, osr          side 0
    0xe93e, //  2: set    x, 30           side 1 [1]
    0x6101, //  3: out    pins, 1         side 0 [1]
    0x0943, //  4: jmp    x--, 3          side 1 [1]
    0xb1e2, //  5: mov    osr, y          side 2 [1]
    0xf93e, //  6: set    x, 30           side 3 [1]
    0x7101, //  7: out    pins, 1         side 2 [1]
    0x1947, //  8: jmp    x--, 7          side 3 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PioI2S_out_program = {
    .instructions = PioI2S_out_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = PioI2S_out_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config PioI2S_out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PioI2S_out_wrap_target, offset + PioI2S_out_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

